# Generated by Django 6.0.1 on 2026-01-22 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "nacionalidad",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("anio", models.IntegerField(verbose_name="Año de Lanzamiento")),
                ("genero", models.CharField(max_length=50)),
                (
                    "portada",
                    models.ImageField(blank=True, null=True, upload_to="portadas/"),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[("V", "Vinilo"), ("C", "CD"), ("D", "Digital")],
                        default="V",
                        max_length=1,
                    ),
                ),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coleccion.artista",
                    ),
                ),
            ],
        ),
    ]
