# Generated by Django 6.0.1 on 2026-02-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coleccion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artista",
            name="nacionalidad",
        ),
        migrations.AddField(
            model_name="disco",
            name="spotify_url",
            field=models.URLField(
                blank=True,
                help_text="Copia el link del álbum desde Spotify (ej: https://open.spotify.com/album/...)",
                null=True,
                verbose_name="Link de Spotify (Opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="artista",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="disco",
            name="anio",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="disco",
            name="formato",
            field=models.CharField(
                choices=[
                    ("V", "Vinilo"),
                    ("C", "CD"),
                    ("D", "Digital"),
                    ("CT", "Cassette"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="disco",
            name="genero",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="disco",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
